name: french_trainer
description: French learning app

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  flutter_tts: ^3.6.3

flutter:
  uses-material-design: true
